language: c++
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src PLATFORMIO_CI_EXTRA_ARGS="--project-conf=platformio.ini --project-option='lib_ignore='"
    - PLATFORMIO_CI_SRC=test PLATFORMIO_CI_EXTRA_ARGS="--project-conf=platformio.ini"

install:
    - pip install --user -U platformio
    - platformio update

script:
    - platformio ci --lib="." $PLATFORMIO_CI_EXTRA_ARGS
