
os: linux

dist: focal

language: c

python:
    - "3.9"

# sudo: false

cache:
    directories:
        - "~/.platformio"
        - $HOME/.cache/pip

env:
    - PLATFORMIO_CI_SRC=src PLATFORMIO_CI_EXTRA_ARGS="--project-conf=platformio.ini"

install:
    - pip3 install --user -U platformio
    - pio update

script:
    - platformio ci --lib="." $PLATFORMIO_CI_EXTRA_ARGS